apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "neo4j"
  labels:
    app: neo4j
    component: replica
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
        component: replica
    spec:
      containers:
      - name: neo4j
        image: "neo4j:3.3.0"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: NEO4J_dbms_mode
            value: READ_REPLICA
          - name: NEO4J_dbms_security_auth__enabled
            value: "false"
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            export NEO4J_dbms_connectors_default__advertised__address=$(hostname -f)
            exec /docker-entrypoint.sh "neo4j"
        ports:
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        - containerPort: 6000
          name: tx
        securityContext:
          privileged: true
